name: 'Docs Request'
description: A request to update or improve documentation
title: 'Docs: '
labels:
  - 'category:docs'
body:
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description: 'Example: I would like to see more examples of how to use the SDK to detect hypercert claim collisions.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://hypercerts.org/docs/api-reference/'
    validations:
      required: false
