name: "Graph CI & testing"

on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install Dependencies
        run: |
          yarn install

      - name: Setup
        run: yarn codegen

      - name: Test
        run: yarn test

      - name: Coverage
        run: yarn coverage
