name: "CI"

# env:
#   INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
#   MNEMONIC: ${{ secrets.MNEMONIC }}

env:
  FOUNDRY_PROFILE: "ci"

on:
  pull_request:
    branches:
      - "main"
      - "dev"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  ci-test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "onbjerg/foundry-toolchain@v1"
        with:
          version: "nightly"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Copy config"
        run: |
          mv ./.env.github .env
          echo "::debug::$(less .env)"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Lint the contracts"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Run the tests and report gas"
        run: "forge test --gas-report"

      - name: "Report test coverage"
        run: "forge coverage"

      - name: "Build the contracts"
        run: |
          forge --version
          forge build --sizes

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn typechain"

      - name: "Hardhat: Test the contracts - primarily UUPS tests"
        run: "yarn test:hardhat"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
