extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./defender/tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true
ignorePatterns: ["build/"]
rules:
  "@typescript-eslint/semi":
    - warn
  "@typescript-eslint/switch-exhaustiveness-check":
    - warn
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "_"
      varsIgnorePattern: "_"
