import { logger } from "./utils";
import {
  getBuiltGraphSDK,
  Sdk as GraphClient,
  execute,
  ClaimsByOwnerDocument,
  ClaimsByOwnerQuery,
  ClaimByIdDocument,
  ClaimByIdQuery,
  RecentClaimsDocument,
  RecentClaimsQuery,
  ClaimsByOwnerQueryVariables,
  ClaimByIdQueryVariables,
  RecentClaimsQueryVariables,
  ClaimTokensByOwnerDocument,
  ClaimTokensByOwnerQuery,
  ClaimTokensByOwnerQueryVariables,
  ClaimTokensByClaimDocument,
  ClaimTokensByClaimQueryVariables,
  ClaimTokensByClaimQuery,
  ClaimTokenByIdDocument,
  ClaimTokenByIdQueryVariables,
  ClaimTokenByIdQuery,
} from "../.graphclient";
import { defaultQueryParams } from "./indexer/utils";
import { HypercertClientConfig, HypercertIndexerInterface, QueryParams } from "./types";

/**
 * A class that provides indexing functionality for Hypercerts.
 *
 * This class implements the `HypercertIndexerInterface` and provides methods for retrieving claims by owner and by ID. It uses the Graph client for indexing.
 * Because of the autogenerated Graph client packed with the SDK, this class is not recommended for custom Graph deployments.
 *
 * @property {GraphClient} _graphClient - The Graph client used by the indexer.
 *
 * @example
 * const indexer = new HypercertIndexer({ graphUrl: 'your-graph-url', graphName: 'your-graph-name' });
 * const claims = await indexer.claimsByOwner('your-address');
 */
export class HypercertIndexer implements HypercertIndexerInterface {
  /** The Graph client used by the indexer. */
  private _graphName: string;

  /**
   * Creates a new instance of the `HypercertIndexer` class.
   * @param options The configuration options for the indexer.
   */
  constructor(options: Partial<HypercertClientConfig>) {
    logger.info("Creating HypercertIndexer", "constructor", { name: options.graphName, url: options.graphUrl });
    if (!options.graphName) throw new Error("Missing graphName");
    this._graphName = options.graphName;
  }

  /**
   * Gets the Graph client used by the indexer.
   * @returns The Graph client.
   */
  get graphClient(): GraphClient {
    return getBuiltGraphSDK({
      graphName: this._graphName,
    });
  }

  /**
   * Gets the claims owned by a given address.
   * @param owner The address of the owner.
   * @param params The query parameters.
   * @returns A Promise that resolves to the claims.
   */
  claimsByOwner = async (owner: string, params: QueryParams = defaultQueryParams) => {
    const query = ClaimsByOwnerDocument;
    const variables: ClaimsByOwnerQueryVariables = {
      owner,
      ...params,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as ClaimsByOwnerQuery;
  };

  /**
   * Gets a claim by its ID.
   * @param id The ID of the claim.
   * @returns A Promise that resolves to the claim.
   */
  claimById = async (id: string) => {
    const query = ClaimByIdDocument;
    const variables: ClaimByIdQueryVariables = {
      id,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as ClaimByIdQuery;
  };
  /**
   * Gets the most recent claims.
   * @param params The query parameters.
   * @returns A Promise that resolves to the claims.
   */
  firstClaims = async (params: QueryParams = defaultQueryParams) => {
    const query = RecentClaimsDocument;
    const variables: RecentClaimsQueryVariables = {
      ...params,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as RecentClaimsQuery;
  };

  /**
   * Gets the claim tokens owned by a given address.
   * @param owner The address of the owner.
   * @param params The query parameters.
   * @returns A Promise that resolves to the claim tokens.
   */
  fractionsByOwner = async (owner: string, params: QueryParams = defaultQueryParams) => {
    const query = ClaimTokensByOwnerDocument;
    const variables: ClaimTokensByOwnerQueryVariables = {
      owner,
      ...params,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as ClaimTokensByOwnerQuery;
  };

  /**
   * Gets the claim tokens for a given claim.
   * @param claimId The ID of the claim.
   * @param params The query parameters.
   * @returns A Promise that resolves to the claim tokens.
   */
  fractionsByClaim = async (claimId: string, params: QueryParams = defaultQueryParams) => {
    const query = ClaimTokensByClaimDocument;
    const variables: ClaimTokensByClaimQueryVariables = {
      claimId,
      ...params,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as ClaimTokensByClaimQuery;
  };

  /**
   * Gets a claim token by its ID.
   * @param fractionId The ID of the claim token.
   * @returns A Promise that resolves to the claim token.
   */
  fractionById = async (fractionId: string) => {
    const query = ClaimTokenByIdDocument;
    const variables: ClaimTokenByIdQueryVariables = {
      claimTokenId: fractionId,
    };
    return (await execute(query, variables, { graphName: this._graphName })) as ClaimTokenByIdQuery;
  };
}
