bracketSpacing: true
endOfLine: "auto"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

plugins:
  - prettier-plugin-solidity

overrides:
  - files: "**/*.t.sol"
    rules:
      max-state-count": "off"
      state-visibility": "off"
      max-line-length": "off"
    options:
      tabWidth: 4
  - files: "*.sol"
    rules:
      compiler-version: "0.8.16"
    options:
      tabWidth: 4
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["importAssertions", "typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
