sources:
  - name: Hypercerts
    handler:
      graphql:
        # Default value is hypercerts-testnet
        # This is needed for the initial introspection on buildtime
        endpoint: https://api.thegraph.com/subgraphs/name/hypercerts-admin/{context.chainName:hypercerts-testnet}

additionalTypeDefs: |
  extend type Claim {
    chainName: String!
  }
   extend type ClaimToken {
    chainName: String!
  }

additionalResolvers:
  - ./src/utils/resolvers.ts

documents:
  - ./src/indexer/queries/*.graphql

codegen:
  contextType: "MeshContext & { chainName: string }"

plugins:
  - pollingLive:
      defaultInterval: 5000
