sources:
  - name: hypercerts
    handler:
      graphql:
        # Default value is hypercerts-testnet
        # This is needed for the initial introspection on buildtime
        endpoint: https://api.thegraph.com/subgraphs/name/hypercerts-admin/{context.chainName:hypercerts-testnet}

additionalTypeDefs: |
  extend type Claim {
    chainName: String!
  }
  extend type ClaimToken {
    chainName: String!
  }
  extend type Query {
    chainName: String!
  }

documents:
  - ./src/queries/*.graphql

codegen:
  contextType: 'MeshContext & { chainName: string }'