#!/bin/bash
python create_hypercert_metadata.py data/projects/ClimateSolutions_ProjectData.csv
python create_hypercert_metadata.py data/projects/EthereumInfrastructure_ProjectData.csv
python create_hypercert_metadata.py data/projects/OpenSourceSoftware_ProjectData.csv

