# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: deploy-os-observer
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - main 
    paths:
      - os-observer/prisma/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-os-observer:
    # NOTE: This name appears in GitHub's Checks API.
    name: deploy-os-observer
    environment: os-observer 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "18.x"
      - name: Install
        run: yarn install --immutable
      - name: Run migrations
        run: yarn deploy:os-observer
