# Builds and pushes docker dependencies used in the hypercerts docker-compose.
name: docker-deps

on: 
  push:
    branches:
      #- main
      - ravenac95/854-* # just filter for this branch for now. FIXME
  workflow_dispatch:
    inputs:
      script_name:
        description: name of the docker script to execute (without the .sh)
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: run build script
        run: |
          bash "docker/scripts/build-playwright.sh"
        env:
          DOCKER_PLATFORM: amd64
