name: os-observer

# Trigger the workflow when:
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: 'fetch-github'
        type: choice
        options:
        - "fetch-github"
        - "fetch-opencollective" 

jobs:
  fetch-data:
    # NOTE: This name appears in GitHub's Checks API.
    name: fetch-data
    environment: os-observer 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: "18.x"
      - name: Install
        run: yarn install --immutable
      - name: Run
        run: yarn start:os-observer ${{ inputs.command }}